server:
    port: 8085

# spring:
#     datasource:
#         url: jdbc:mysql://host.docker.internal:3306/expense_manager?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
#         username: root
#         driver-class-name: com.mysql.cj.jdbc.Driver
#     jpa:
#         open-in-view: false
#         database-platform: org.hibernate.dialect.MySQL55Dialect
spring:
    datasource:
        url: jdbc:mysql://129.153.190.89:3306/expense_manager?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
        username: user
        password: password
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        open-in-view: false
        database-platform: org.hibernate.dialect.MySQL55Dialect