server:
    port: 8085

spring:
    datasource:
        url: jdbc:mysql://129.153.190.89:3306/db?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
        username: user
        password: password
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        open-in-view: false
        database-platform: org.hibernate.dialect.MySQL55Dialect