
spring:
    application:
        name: expenses
    profiles:
        # active: dev
        active: @profile.active@

# encrypter:
#     salt: //]ncX?001!@bc3&

# microservice-common.url: host.docker.internal:8000